development:
  adapter: mysql2
  database: stockxchange_project
  username: root
  password:
  host: 127.0.0.1
  #socket: /var/lib/mysql/mysql.sock
test:
   adapter: mysql2
   database: stockxchange_test
   username: root
   password:
   host: 127.0.0.1

production:
   adapter: mysql2
   database: stockxchange_production
   username: root
   password:
   host: 127.0.0.1
  
