# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 148ef47c90698adbc5861105e54d7e041adc4bba376e2b7472a70d48a4180adc72d89e995817f03508a8491380906caf9e5ae099a946171a70bdb4d55406e0f6

test:
  secret_key_base: e0885508808bd6d23b5cb06f2409d4373b6a48049a364eb7c5dc43f05a33faf3c8c7d2c21d6d669d928e873165f318c672938bbe8637a4aff4742a9d638c9abc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
